### PR TITLE
Fix conditions query

### PR DESCRIPTION
**Pull request by a1tem**
Before this change, the query was wrong, and as a result, I always got the error

### CODE REVIEW

**Comment by coderaf** [comment]
Thankx @a1tem to be honest we had never chance to use it. And there is no unit tests for it.

**Comment by timwsuqld** [comment]
@a1tem @coderaf This new logic breaks the previous functionality. Previously, you could pass through a bunch of where conditions (both `=` and `!=`), now you can only pass in conditions for `=`

```php
// How to query before this commit
$api->query($fields, 'Account', [
            "RecordTypeId = 'AXZ'",
        ]);
// After the commit, it becomes
$api->query($fields, 'Account', [
            "RecordTypeId" => "AXZ",
        ]);

// However there is no way to do the following due to this commit, and this was possible before
$api->query($fields, 'Account', [
            "RecordTypeId != 'AXZ'",
        ]);
```

We've been using this library for a few years now, so maybe the issue was with the documentation? Most of the other commands use an assocaitive array syntax, where the query command required you to construct the where clauses yourself. It would probably make more sense to revert this comment and update the documentation, as otherwise the way to support `!=` would require a more convulated array of conditions.

**Comment by coderaf** [comment]
hey @timwsuqld you sure you could use something like this ` "RecordTypeId != 'AXZ'",` becuase those queries goes to http query, you sure you dont use something more like this ` "RecordTypeId+!=+'AXZ'"` ?

**Comment by coderaf** [comment]
anyway i commited change to master, which accepts both cases https://github.com/genesis-global/salesforce-bundle/commit/88785714b7e4e9b60db84eaa9340346e7df336a2

**Comment by timwsuqld** [comment]
@coderaf Sorry for the late response, thanks for updating to support both use cases.

**Pull request merged**
