### PR TITLE
Fixed compatibility with Symfony 4

### PR DESCRIPTION
**Pull request by clamburger**
Fixes three issues that throw exceptions in Symfony 4:

- ->cannotBeEmpty() is not applicable to concrete nodes at path "salesforce.authentication". 
- ->cannotBeEmpty() is not applicable to concrete nodes at path "salesforce.rest".
- The configuration key "private" is unsupported for service definition "salesforce.response_creator"

### CODE REVIEW

**Comment by coderaf** [comment]
Those configuration is used in GenesisGlobal\Salesforce\SalesforceBundle\DependencyInjection\SalesforceExtension, thats why its required.

Its a good point to make it optional, but it needs some more changes.

**Comment by coderaf** [comment]
"Corrected private: true to public: false " is approved as it is

**Comment by clamburger** [comment]
It's my understanding that `cannotBeEmpty` has no effect on array configuration nodes, which is why using it throws an exception in Symfony 4.

Because the `authentication` and `rest` nodes have `isRequired`, and all of the child nodes have `isRequired` and `cannotBeEmpty`, the user is still required to fill in all of the configuration options, and attempting to omit any will still result in an error.

If you'd like, I can write some tests that validate the correct behaviour?

**Comment by coderaf** [comment]
Now i see what you meant. I've checked it on symfony 3.4 and it was ok. No exception at all. But It actualy has no use there, so i can remove it.

**Pull request merged**
